version: '3.9'

services:
    postgres:
        image: postgres:latest
        container_name: postgres_container
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user111
            POSTGRES_DB: lara_db
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 256M
        command: >
            postgres -c max_connections=1000
                     -c shared_buffers=256MB
                     -c effective_cache_size=768MB
                     -c maintenance_work_mem=64MB
                     -c checkpoint_completion_target=0.7
                     -c wal_buffers=16MB
                     -c default_statistics_target=100
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: unless-stopped
        tty: true
        stdin_open: true

volumes:
    pgdata:
        driver: local











#version: '3.3'
#services:
#    db:
#        image: mysql:5.7
#        restart: always
#        environment:
#            MYSQL_DATABASE: 'db'
#            # So you don't have to use root, but you can if you like
#            MYSQL_USER: 'user'
#            # You can use whatever password you like
#            MYSQL_PASSWORD: 'password'
#            # Password for root access
#            MYSQL_ROOT_PASSWORD: 'password'
#        ports:
#            # <Port exposed> : <MySQL Port running inside container>
#            - '3306:3306'
#        expose:
#            # Opens port 3306 on the container
#            - '3306'
#            # Where our data will be persisted
#        volumes:
#            - my-db:/var/lib/mysql
## Names our volume
#volumes:
#    my-db:
